name: $(Build.DefinitionName)_$(Date:yyyy).$(Date:%M).$(Date:%d)$(Rev:.r)
trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: CICD
      type: github
      ref: main
      name: nhatthaiquang-agilityio/Terraform-CI-CD
      endpoint: nhatthaiquang-agilityio

variables:
  - name: AzureServiceConnection
    value: 'AzureServiceConnection'
  - name: AzureFunctionName
    value: 'example-az-func'
  - name: PackagePath
    value: '$(Agent.BuildDirectory)/drop/$(Build.BuildNumber).zip'
  - name: TerraformInfraWorkingDirectory
    value: '$(System.DefaultWorkingDirectory)/DevOps/Terraform/Infrastructures'
  - name: TerraformStateStorageAccount
    value: 'tfstateazfunc'
  - name: TerraformStateStorageAzureResourceGroup
    value: 'RG-ExampleAzureFunctions'
  - name: TerraformStateStorageContainer
    value: 'tfazfunc'
  - name: TerraformStateStorageInfrastructureFilename
    value: 'infrastructure.tfstate'

stages:
  - stage: SetupInfraTest
    displayName: Setup Infrastructure in Test
    jobs:
    - template: jobs/setup-azure-infrastructure.yml@CICD
      parameters:
        EnvironmentName: 'Test'
        TerraformWorkingDirectory: ${{ variables.TerraformInfraWorkingDirectory }}
        AzureServiceConnectionName: ${{ variables.AzureServiceConnection }}
        StorageAccountsName:  ${{ variables.TerraformStateStorageAccount }}
        AzureResourceGroupName: ${{ variables.TerraformStateStorageAzureResourceGroup }}
        AzureContainerName: ${{ variables.TerraformStateStorageContainer }}
        AzureRmKeyTFState: test.${{ variables.TerraformStateStorageInfrastructureFilename }}
