name: $(Build.DefinitionName)_$(Date:yyyy).$(Date:%M).$(Date:%d)$(Rev:.r)
trigger: none
pr: none

resources:
  repositories:
    - repository: CICD
      type: github
      ref: main
      name: nhatthaiquang-agilityio/Terraform-CI-CD
      endpoint: nhatthaiquang-agilityio

variables:
  - name: AzureServiceConnection
    value: 'AzServicePrincipal'
  - name: AzureFunctionName
    value: 'example-az-func'
  - name: PackagePath
    value: '$(Agent.BuildDirectory)/drop/$(Build.BuildNumber).zip'
stages:
  - stage: build
    displayName: Build
    pool: azagent-deployment
    jobs:
      - template: jobs/build-dotnet.yml@CICD
        parameters:
          BuildTargetPath: '**/ExampleAzureFunctions.csproj'
          DotNetVersion: '8.x'

  - stage: deploy
    displayName: Deploy Test
    dependsOn: build
    pool: azagent-deployment
    jobs:
      - template: jobs/deploy-azure-function.yml@CICD
        parameters:
          EnvironmentName: Test
          AzureSubscription: '${{ variables.AzureServiceConnection }}'
          AzureFunctionName: '${{ variables.AzureFunctionName }}'
          PackagePath: ${{ variables.PackagePath }}