environment = "test"
location="SouthEast Asia"
resource_group_name="RG-ExampleAzureFunctions"
az_function_storage_account_name="stdexampleazfunc"
azurerm_windows_function_app_name="example-az-func"
az_function_pv_svc_connection="pe-svc-exampleazfunc"
pv_endpoint_name="pe-func-exampleazfunc"
